Ads.MVC/Controllers/FollowerController.cs
using Ads.Application.Commands;
using Ads.Application.Dto;
using Ads.DataAccess.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Ads.MVC.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class FollowerController : Controller
    {
        private readonly ICreateRemoveFollowerCommand _createRemoveFollowerCommand;
        private readonly UserManager<ApplicationUser> _userManager;

        public FollowerController(ICreateRemoveFollowerCommand createRemoveFollowerCommand, UserManager<ApplicationUser> userManager)
        {
            _createRemoveFollowerCommand = createRemoveFollowerCommand;
            _userManager = userManager;
        }

        [HttpPost]
        public ActionResult Update(int AdId)
        {
            _createRemoveFollowerCommand.Execute(new CreateFollowerDto()
            {
                AdId = AdId,
                UserId = GetUserId().Result
            });
            return RedirectToAction("Index", "Home");
        }
        private async Task<string> GetUserId()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return user.Id;
        }
    }
}

Ads.MVC/Controllers/HomeController.cs
using Ads.Application.Commands;
using Ads.Application.Dto;
using Ads.Application.Searches;
using Ads.DataAccess.Domain;
using Ads.MVC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Ads.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGetAdsCommand _listAdCommand;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGetCategoriesCommand _categoryCommand;
        private readonly ICreateAdCommand _createAdCommand;
        private readonly IDeleteAdCommand _deleteAdCommand;
        private readonly IEditAdCommand _editAdCommand;

        public HomeController(IGetAdsCommand listAdCommand,
            UserManager<ApplicationUser> userManager,
            IGetCategoriesCommand categoryCommand,
            ICreateAdCommand createAdCommand, IDeleteAdCommand deleteAdCommand, IEditAdCommand editAdCommand)
        {
            _listAdCommand = listAdCommand;
            _userManager = userManager;
            _categoryCommand = categoryCommand;
            _createAdCommand = createAdCommand;
            _deleteAdCommand = deleteAdCommand;
            _editAdCommand = editAdCommand;
        }

        public IActionResult Index(AdSearch model)
        {
            return View(GetAds(model));
        }

        [HttpGet]
        public ActionResult Add(CategorySearch search)
        {
            ViewData["Categories"] = new SelectList(GetCategories(search), "Id", "Name");
            return View();
        }

        private IEnumerable GetCategories(CategorySearch search)
        {
            return _categoryCommand.Execute(search);
        }

        [HttpPost]
        public ActionResult Add(CreateAdDto request)
        {
            try
            {
                request.UserId = GetUserId().Result;
                _createAdCommand.Execute(request);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int? id, AdSearch search)
        {
            var ads = _listAdCommand.Execute(search);
            var singleAd = ads.Where(w => w.Id == id).First();
            return View(singleAd);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, DeleteAdDto model)
        {
            model.Id = id;
            model.UserId = GetUserId().Result;
            _deleteAdCommand.Execute(model);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id, AdSearch search)
        {
            var ads = _listAdCommand.Execute(search);
            var editAd = ads.Where(w => w.Id == id).SingleOrDefault();
            return View(new CreateAdDto()
            {
                Id = editAd.Id,
                Subject = editAd.Subject,
                Description = editAd.Description
            });
        }

        [HttpPost]
        public ActionResult Edit(int id, [Bind("Subject", "Description")]CreateAdDto model)
        {

            _editAdCommand.Execute(new EditAdDto()
            {
                Id = id,
                Description = model.Description,
                Subject = model.Subject,
                UserId = GetUserId().Result,
            });
            return RedirectToAction("Index");
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private IEnumerable<AdListDto> GetAds(AdSearch request)
        {
            if (User.Identity.IsAuthenticated)
            {
                request.FollowerUserId = GetUserId().Result;
            }
            return _listAdCommand.Execute(request);
        }

        private async Task<string> GetUserId()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return user.Id;
        }

    }
}

Ads.MVC/Controllers/OfferController.cs
using Ads.Application.Commands;
using Ads.Application.Dto;
using Ads.Application.Searches;
using Ads.DataAccess.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Ads.MVC.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class OfferController : Controller
    {
        private readonly IGetOfferByIdCommand _getOfferByAdIdCommand;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICreateOfferCommand _createOfferCommand;
        private readonly IGetOfferCommand _getAllUserOffers;
        private readonly IDeleteOfferCommand _deleteOfferCommand;

        public OfferController(IGetOfferByIdCommand getOfferByAdIdCommand,
            UserManager<ApplicationUser> userManager,
            ICreateOfferCommand createOfferCommand,
            IGetOfferCommand getAllUserOffers,
            IDeleteOfferCommand deleteOfferCommand)
        {
            _getOfferByAdIdCommand = getOfferByAdIdCommand;
            _userManager = userManager;
            _createOfferCommand = createOfferCommand;
            _getAllUserOffers = getAllUserOffers;
            _deleteOfferCommand = deleteOfferCommand;
        }

        [HttpGet("{id}")]
        public ActionResult Index(int id)
        {
            ViewData["AdId"] = id;
            var response = _getOfferByAdIdCommand.Execute(new OfferSearch()
            {
                AdId = id,
                UserId = GetUserId().Result
            });
            return View(response);
        }


        [HttpPost]
        public ActionResult Create(CreateOfferDto offer)
        {
            try
            {
                offer.AdId = offer.AdId;
                offer.UserId = GetUserId().Result;
                _createOfferCommand.Execute(offer);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                return StatusCode(500, e.Message);
            }
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var response = _getAllUserOffers.Execute(new OfferSearch()
            {
                UserId = GetUserId().Result

            });

            var currentOffer = response.SingleOrDefault(w => w.Id == id);
            return View(currentOffer);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, DeleteAdDto model)
        {
            model.Id = id;
            model.UserId = GetUserId().Result;
            _deleteOfferCommand.Execute(new DeleteOfferDto()
            {
                Id = model.Id,
                UserId = model.UserId
            });
            return RedirectToAction("Index", "Home");
        }

        private async Task<string> GetUserId()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return user.Id;
        }
    }
}

Ads.MVC/Views/Home/Add.cshtml
@model Ads.Application.Dto.CreateAdDto
@{
    ViewData["Title"] = "Add";
}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

<form asp-action="Add">
    <div class="form-group">
        <label class="control-label">Category</label>
        <select class="form-control" id="CategoryId" name="CategoryId" asp-items="@ViewBag.Categories">
            <option value="0">Please Select</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Subject">Subject</label>
        <input class="form-control" asp-for="Subject" />
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input class="form-control" asp-for="Description" />
    </div>

    <div class="form-group">
        <input type="submit" class="form-control" value="Save" />
    </div>
</form>

Ads.MVC/Views/Home/Delete.cshtml
@model Ads.Application.Dto.AdListDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Ads.MVC/Views/Home/Edit.cshtml
@model Ads.Application.Dto.CreateAdDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Ad</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Ads.MVC/Views/Home/Index.cshtml
@model IEnumerable<Ads.Application.Dto.AdListDto>
@{
    ViewData["Title"] = "Index";
}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<div class="jumbotron">
    <form method="get" asp-action="Index">
        <input class="form-control" type="text" name="Subject" placeholder="Subject Search" />
        <input class="form-control" name="Description" placeholder="Description Search" />
        <input class="form-control" name="CategoryName" placeholder="Category Search" />
        <input type="submit" class="btn btn-success mt-2" value="Search" />
        <input type="submit" class="btn btn-success mt-2" id="clearFilter" value="Clear Filter" />
    </form>
</div>
@if (User.Identity.IsAuthenticated)
{
    <div>
        <a class="btn btn-success mb-3" asp-action="Add">Create New</a>
    </div>
}
<div class="row">


    @foreach (var element in Model)
    {
        <div class="col-4">
            <div class="card mr-2 mt-2">
                <div class="card card-header">
                    #@element.Id
                </div>

                <div class="card-body">
                    <div class="card-text"><span class="text-black-50 font-weight-bold">Subject</span> @element.Subject</div>
                    <div class="card-text"><span class="text-black-50 font-weight-bold">Description</span> @element.Description</div>
                    <div class="card-text"><span class="text-black-50 font-weight-bold">Category</span> @element.CategoryName</div>
                    <div class="card-text"><span class="text-black-50 font-weight-bold">Created By</span> @element.UserName</div>
                </div>
                <div class="card-footer">
                    <ul class="list-inline">
                        @if (User.IsInRole("Admin") || User.Identity.Name == element.UserName)
                        {
                            <li class="list-inline-item"><a asp-action="Delete" asp-controller="Home" asp-route-id="@element.Id">Delete</a></li>
                            <li class="list-inline-item"> <a asp-action="Edit" asp-controller="Home" asp-route-id="@element.Id">Edit</a></li>

                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="list-inline-item"><a asp-controller="Offer" asp-action="Index" asp-route-id="@element.Id">Offer</a> </li>
                            if (element.IsFollowed)
                            {
                                <li class="list-inline-item"><form asp-controller="Follower" asp-action="Update">
                                    <input type="hidden" asp-for="@element.Id" name="AdId"  />
                                    <button class="btn btn-primary" type="submit">UnFollow</button>
                                </form> </li>
                            }
                            else
                            {
                                <li class="list-inline-item"><form asp-controller="Follower" asp-action="Update">
                                    <input type="hidden" asp-for="@element.Id" name="AdId" />
                                    <button class="btn btn-primary" type="submit">Follow</button>
                                </form> </li>
                            }                                       
                            

                        }
                        <li class="list-inline-item"><a asp-controller="Comments" asp-action="Index" asp-route-id="@element.Id">Comments</a></li>
                    </ul>
                </div>
            </div>

        </div>

    }

</div>
<script>
    document.getElementById('clearFilter').onclick = function (event) {
        var inputs = document.getElementsByTagName('input');
        for (var i = 0; i < inputs.length; i++) {
            if (inputs[i].type == "text") {
                inputs[i].value = "";
            }
        }

    }</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}